apache/cordova-plugin-splashscreen

README.md
plugin.xml
src/browser/SplashScreenProxy.js

Added Browser platform support
Using cordova/confighelper module to read parameter values from config.xml
Updated the docs
configHelper for exposing `config.xml` related [JIRA issue](https://issues.apache.org/jira/browse/CB-8223) and PRs: [cordova-lib/browser_parser.js](https://github.com/apache/cordova-lib/pull/149), [cordova-browser/cordova.js](https://github.com/apache/cordova-browser/pull/7).

CB-7964 Add cordova-plugin-splashscreen support for browser platform

---

src/wp/SplashScreen.cs

If you have an element that shares the `name`, like `<feature name="SplashScreen">`, then the `value` attribute was read of that instead (since it can appear *before* the preference element). Thus, the config of `SplashScreen` preference was not settable at all.

WP8: Avoid config `value` of a wrong element.

---

src/ios/CDVSplashScreen.m

Don't rotate the iPhone 6 Plus splash
Fixes 2 orientation change-related issues.
[CB-9043](https://issues.apache.org/jira/browse/CB-9043)
[CB-10244](https://issues.apache.org/jira/browse/CB-10244)

CB-9043 CB-10244 Fix the ios splashscreen being deformed on orientation change

---

src/ios/CDVViewController+SplashScreen.m

[Jira issue](https://issues.apache.org/jira/browse/CB-9240)
Aligns `shouldAutorotate` default value with [parent CDVViewController behavior](https://github.com/apache/cordova-ios/blob/d3c5519719d172bfcf6d994c740615b6fdfa91e6/CordovaLib/Classes/Public/CDVViewController.m#L352-L355).
This fix also does not break iPhone rotation behavior - it's being turned on after splashscreen hide and swizzling dismissal.

CB-9240 Cordova splash screen plugin iPad landscape mode issue

---

README.md
src/android/SplashScreen.java

FadeSplashScreen is supported by using AlphaAnimation to fade out the ImageView.
Based on #53 
Documented the `FadeSplashScreenDuration` preference usage.
[Jira issue](https://issues.apache.org/jira/browse/CB-9538)

CB-9538 Implementing FadeSplashScreen feature for Android

---

src/android/SplashScreen.java

[Jira issue](https://issues.apache.org/jira/browse/CB-8396)
Also initializing the splashscreen image irrespective of firstShow because the splashscreen could be shown manually via navigator.splashscreen.show(); after exiting the app using BackButton or via navigator.app.exitApp(); - otherwise the image would be uninitialized.

CB-8396 Add AutoHideSplashScreen logic to Android's Splashscreen

---

README.md
src/android/SplashScreen.java

[Jira issue](https://issues.apache.org/jira/browse/CB-9516)
Removes spinnerStop call from onMessage("spinner", "stop") as it is called when webview is shown and we are hiding spinner manually along with the splashscreen dialog.
Changed the spinner to be noncancellable.
Changed the ProgressDialog to custom only-spinner mode (on transparent background, without title/message and dimming).
Removed unused spinnerStart action handler.
Updated the docs.

CB-9516 Android SplashScreen - Spinner Does Not Display

---

README.md
package.json
plugin.xml
www/windows/SplashScreenProxy.js

[Jira issue](https://issues.apache.org/jira/browse/CB-8056)
The plugin implementation has been moved to the platform code
Documented SplashScreenBackgroundColor preference for Windows
Updated the docs
Related to apache/cordova-windows#141

CB-8056 Implement splashscreen for Windows platform

---

src/android/SplashScreen.java

- Android
Fixes app hang (due to internal crash) after calling `navigator.app.loadUrl(myurl)`
Manual testing

CB-11326 Prevent crash when initializing plugin after navigating to another URL

---

README.md

iPhone 5, 5s, and SE have resolution 640x1136, not 640x960 as currently documented.

Fix CB-12947 (incorrect documentation of iPhone 5 and 5s resolution)

---

src/ios/CDVSplashScreen.h
src/ios/CDVSplashScreen.m

iOS
Takes into account iPhone X sizes for splash screen
Tested on iPhone X

CB-13737 (iOS): fix Splash screen images for iPhone X

---

.travis.yml

travis
Add build-tools-26.0.2 so travis doesn't complain about unaccepted licenses

CB-13750: Add build-tools-26.0.2 to travis

---

.travis.yml
package.json

none
- Match Paramedic Test
- Update Package.json
- Updated Travis CI to test local and same set of platforms that paramedic tests.
- Updated package.json

Updated Travis CI Settings and Package.json

---

.travis.yml

none
Revert the usage of a dev branch of paramedic
Revert the usage of a dev branch of paramedic
none

Revert Paramedic Dev Branch Usage

---

README.md

iOS & Android
- Notify users to use new storyboard for ios.
- Adding port & land xxxhdpi splash screen size for android.

Update readme.md by adding missing info

---

package.json

Fixes #235 
Change was requested in issue #235

Fixes #235: update homepage to github readme page

---

tests/ios/package.json

iOS
- Force tests to use Cordova-iOS 5.1.1
- Using PR Test Run

test: force cordova-ios@^5.1.1

---

package.json

all
Bump the engine restriction of Cordova dependency so that the next version of the plugin can install.
* Changed version `6.0.0` to `7.0.0`
- Check CI Services Test Results

breaking: bump engine restriction for cordova dependencies

---

package.json

* In a production environment, our plugins do not execute node related code and does not need the engine check.
* In the environment of developing this plugin, the linting tool is the only node based library which has already defined the node engine requirement. We do not need to set the engine since the lint tool will report, when not valid.
**Example:**
> npm WARN notsup Unsupported engine for @cordova/eslint-config@3.0.0: wanted: {"node":">= 10.13.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
> npm WARN notsup Not compatible with your version of node/npm: @cordova/eslint-config@3.0.0

breaking: drop node engine requirement

---

package.json

In plugin.xml we still require cordova-android >=3.6.0 and cordova-windows >=4.4.0, but the engines in package.json are not updated since version 4 and not taken into account on version 5 and 6.
So changing the 4.0.0 to >=4.0.0 it should cover 5 and 6 too

chore: update engine checks to cover newer versions

---

package.json

npm keywords was missing `cordova-browser` as a supported platform. This PR added the keyword.

chore: add missing supported platform browser to npm keywords

---

README.md

various improvements including size specs
closes #270
closes #260

doc(android): various improvements including size specs

---

plugin.xml

all
The shared JS content is being clobbered on all platforms even if the platform is not supported.
iOS is affected by this clobber because it has its own JS file that is clobbered on the same `window.navigator` scope.
Move the shared JS clobber into each defined platform until a better solution is implemented to be more strict on plugin installs.
- plugin install & simulator run
- With mobile spec
- Without mobile spec
- With changes
- With out changes

fix: js clobber only on supported platforms

---

README.md

Just a Documentation Change
Dark Mode SplashScreens now work on both: iOS and Android. To let people know how to use them i created this documentation change. #246

(docs): Add Information about how to use Dark Mode SplashScreens

---

README.md

Docs
Updated iOS supported platform documentation to hopefully clarify some confusion as shown [here](https://github.com/apache/cordova-plugin-splashscreen/issues/299#issuecomment-710787527) and [here](https://github.com/apache/cordova-plugin-splashscreen/commit/faa8aa937d398f08b1a4ddab6486e4ca5e39517b#commitcomment-43325462)
Add mention that if you're using `cordova-ios@5` then you should remain on version 5 of this plugin. If you're using `cordova-ios@6` then you should be using version 6 of this plugin, or if you're developing exclusively for iOS, then it's safe to uninstall this plugin altogether.
Please let me know if the wording should be altered.

docs: Added iOS notes to supported platforms.

---

README.md

Android
Just add missing `night` word in the file names of images.

[Android] [Enhancement] [Docs] Add missing (night) to file names of images

---

README.md

Disclaimer: This is an almost 1 to 1 copy of [228](https://github.com/apache/cordova-plugin-splashscreen/pull/228) that was closed on a technicality 
Only docs
Current documentation lacks the default resources for Android.
On Android, you can provide alternative resources for specific device configuration, like current docs provide alternative resources for portrait and landscape orientation. But error will be thrown if a device configuration does not match any specific alternative resources, so you should provide a default (In this case, without port- or land- ) as a fallback.
This change fixes the error reported in #185 and [apache/cordova-android#689](https://github.com/apache/cordova-android/issues/689).
[Although orientation is only portrait and landscape as of …

chore(docs): Update missing  default resources for Android #689

---

src/android/SplashScreen.java

android
After Android SDK 28, the android buck-button key event can not be handled. 
This issue happens because the webview gets out of focus.
This PR made the webview to refocus after url loading.
fixes: #186
In my local environment I tested by creating sample app with cordova-android 9.1.0 and cordova 10.0.0.
I also run ` npm run test`.

fix: refocus after webview visible (#186)

---

src/android/SplashScreen.java

Android
simple input with autofocus doesn't get focus on startup on Android > 8
requestFocus on webview after restore visibility

Fix(android): autofocus don't work after splashscreen

---

src/android/SplashScreen.java

Android
This is a fix for https://github.com/apache/cordova-plugin-splashscreen/issues/180
The issue is that when the app is supposed to be in fullscreen mode, the nav and title bars still display while the splashscreen is visible.
Cordova's main activity currently doesn't set the fullscreen flag until it gets focus, so when we check it on plugin init, it's always false. I've added a fallback to read the `Fullscreen` preference if cordova hasn't set flags yet. Long term, I'm planning on doing a separate PR to the cordova-android repo to fix it so that it sets it in `onCreate` instead.
Note: The issue is 90% fixed, but the nav and title bars still flash in briefly when the splashscreen hides. This is because cordova's activity hasn't set its view flags yet and hasn't gotten focus yet. The …

fix(android): hide nav & title bars when fullscreen is enabled

---

README.md
package-lock.json
package.json
plugin.xml

Android
The Cordova Android platform has inegrated the Splash Screen plugin as core functionality.
This plugin is no longer needed in in the next majpr release of Cordova Android (11.0.0+).
Update the engine requirement to not install on 11.0.0 or above.

chore: update android engine requirement <11.0.0

---

README.md

Splash Screen has been migrated as a core feature of the iOS platform.
This PR is to remove the documentation from the plugin repo and remove any confusion that the plugin still supports iOS.
The iOS related documentation is being migrated to [`cordova-docs`](https://github.com/apache/cordova-docs/pull/1249)
Cleanup README

doc(readme): remove iOS docs (migrated to cordova-docs)
