src/wp/SplashScreen.cs
Extend WP8 Splash Screen to respect SplashScreen and SplashScreenDelay preferences from config file
=> [WP8] Respect SplashScreen and SplashScreenDelay preferences from config file

www/windows/SplashScreenProxy.js
[Jira issue](https://issues.apache.org/jira/browse/CB-9467)
=> CB-9467 SplashScreen does not show any image in hosted app on Windows 10

src/ios/CDVSplashScreen.m
fixes some weak/strong self identity + confidence issues
=> CB-8875 FadeSplashScreen was not fading

src/ios/CDVSplashScreen.m
[Jira issue](https://issues.apache.org/jira/browse/CB-10231)
=> CB-10231 Fix FadeSplashScreen to default to true on iOS

src/android/SplashScreen.java
[Jira issue](https://issues.apache.org/jira/browse/CB-10422)
=> CB-10422 Splashscreen displays black screen with no image on Android

.jshintrc, .travis.yml, README.md, package.json, src/blackberry10/index.js, src/browser/SplashScreenProxy.js, src/tizen/SplashScreenProxy.js, tests/tests.js, www/windows/SplashScreenProxy.js
[CB-10636 Add JSHint for plugins](https://issues.apache.org/jira/browse/CB-10636)
[CB-10650 Non-index content.src causes Splashscreen to be not displayed on browser](https://issues.apache.org/jira/browse/CB-10650)
=> CB-10636 CB-10650 Add JSHint for plugins

README.md
Removing warning emoji
@dblotsky @riknoll @rakatyal Can you please review and merge this PR?
=> CB-10764: Remove emoji in cordova-plugin-splashscreen

.travis.yml, tests/ios/package.json
Updated cordova-ios tests dependency version to latest published
[Jira issue](https://issues.apache.org/jira/browse/CB-10864)
=> CB-10864 Run ios native tests on Travis

src/ios/CDVSplashScreen.h, src/ios/CDVSplashScreen.m
[Jira issue](https://issues.apache.org/jira/browse/CB-10562)
=> CB-10562 hide() not working in latest splashscreen plug in 3.1.0 in iOS

.jshintignore, tests/ios/package.json
Added jshintignore for tests/ios
[Jira issue](https://issues.apache.org/jira/browse/CB-10979)
=> CB-10979 Fix splashscreen ios native tests

README.md
[Jira issue](https://issues.apache.org/jira/browse/CB-6498)
This is constantly causing confusion:
http://stackoverflow.com/questions/36575576/cordova-splash-screen-plugin
http://stackoverflow.com/questions/25513126/cordova-3-4-splashscreen-not-working?rq=1
http://stackoverflow.com/questions/36181366/splashscreen-doesnt-work-with-cordova-6-0-0
=> CB-6498 Misleading documentation in Android Quirks

README.md, package.json, plugin.xml
Related to https://github.com/apache/cordova-windows/pull/172
=> CB-8056 Updated the dependency version, added it to the docs

.travis.yml, README.md, src/android/SplashScreen.java, src/ios/CDVSplashScreen.m
Updated the docs
[Jira issue](https://issues.apache.org/jira/browse/CB-11156)
=> CB-11156 Change default FadeSplashScreenDuration value

README.md
[Jira issue](https://issues.apache.org/jira/browse/CB-11751)
Document that splashscreen needs to be disabled on Windows in case of updating entire document body
=> CB-11751 'extendedSplashScreen' is undefined

package.json
=> CB-13709: Fix to allow 5.0.0 version install

README.md
=> Fixed docs typo

.travis.yml
=> CI: Use universal paramedic travis.yml

.travis.yml
=> Travis CI: Add ADDITIONAL_TESTS_DIR=./tests/ios

package.json, plugin.xml, tests/package.json, tests/plugin.xml
Prepare for next major release
* Requires #261 to be merged
=> breaking: bump version 6.0.0-dev

package.json
Related to https://github.com/apache/cordova/issues/55
=> chore(pkg): remove default-valued field "homepage"

RELEASENOTES.md
=> docs: fixup spaces for releasnotes

.github/workflows/android.yml
n/a
Sync the GH Action Workflow with match with cordova-paramedic (source of truth)
Copy over Android & iOS CI Workflow configs
N/A
=> ci: sync workflow with paramedic

package-lock.json, package.json, plugin.xml, tests/package.json, tests/plugin.xml
Bump for major development 7.0.0
bump to 7.0.0-dev
=> chore: bump to 7.0.0-dev

package-lock.json, package.json
n/a
restore ios engine requirement
updated package.json and package-lock.json
n/a
=> fix(ios): restore engine requirement
